export interface Letter {
  title: string;
  author: string;
  dateStart: string;
  dateEnd: string;
  paragraphs: string[];
}

export const letterData: Letter = {
  title: "Uma carta que eu precisava escrever",
  author: "Benjamim",
  dateStart: "18/07, às 18:32",
  dateEnd: "20/07, às 16:28",
  paragraphs: [
    "Ana,",
    "Antes de qualquer coisa, eu quero que você entenda que esta carta não foi escrita para falar mal de você, apontar seus erros ou fazer você se sentir culpada por alguma coisa. Também não quero que você leia estas palavras como uma acusação.",
    "Eu escrevi porque existem coisas que eu tenho guardado há algum tempo e que, de alguma forma, eu precisava conseguir colocar em palavras. Talvez conversando eu não conseguisse dizer tudo isso. Talvez eu desistisse no meio. Então preferi escrever.",
    "Eu nunca esqueci dos momentos em que fui rejeitado, das coisas que ouvi sobre mim e das vezes em que percebi que havia machucado alguém sem sequer perceber o quanto estava sendo inconveniente. Durante muito tempo tentei simplesmente evitar essas situações, como se fugir delas fosse suficiente para mudar quem eu sou.",
    "Lembra da Ana Beatriz?",
    "Era bastante óbvio que eu gostava dela. Ela foi sincera comigo, e, apesar de algumas coisas terem doído, a sinceridade dela não fez com que eu deixasse de considerá-la uma pessoa importante.",
    "No meu aniversário, em 28/04, eu havia combinado de sair com ela para comemorar. Quando ela não pôde ir, eu acabei reagindo de uma maneira da qual hoje não me orgulho. Eu estava começando a me tornar aquele tipo de pessoa que acredita que precisa ser importante o tempo inteiro, e acabei falando demais, me vitimizando e colocando sentimentos meus sobre uma situação que não deveria ter se tornado tão grande.",
    "Foi então que ouvi uma coisa que, mesmo tendo doído, eu entendi.",
    "Eu posso ser inconveniente.",
    "E não digo isso para fazer drama ou para que você tenha pena de mim. Digo porque reconheço que já fui assim. Já fiz pessoas ficarem mal por causa da minha imaturidade. Já fiz promessas que não cumpri. Já disse que iria mudar e, mesmo assim, acabei repetindo os mesmos erros.",
    "E talvez o mais difícil seja admitir que reconhecer isso não significa que eu já saiba como mudar.",
    "Eu me lembro de coisas pequenas também. Até daquele dia em que você me bateu com um caderno. Pode parecer uma lembrança boba, mas, de alguma maneira, ela ficou na minha cabeça. Às vezes eu penso em situações assim e me pergunto:",
    "Por que eu ainda consigo ser tão infantil?",
    "Eu tenho dificuldade em gostar de alguém sem deixar que esse sentimento tome conta de mim.",
    "Tenho dificuldade em aceitar que uma pessoa pode ser importante para mim sem precisar ser minha prioridade. Quero atenção, quero respostas, quero sentir que sou importante, quero ouvir determinadas coisas e, quando não recebo aquilo que espero, começo a pensar demais.",
    "E eu sei que isso pode ser cansativo.",
    "Sei que, quando esses sentimentos crescem, existe o risco de eu acabar tentando controlar aquilo que nunca deveria estar sob meu controle: a maneira como outra pessoa sente, responde ou escolhe estar comigo.",
    "Eu não quero me tornar alguém possessivo.",
    "Não quero que uma pessoa que um dia foi importante para mim comece a sentir medo, cansaço ou até raiva por minha causa.",
    "E, principalmente, não quero esperar que você suporte uma versão minha que eu mesmo ainda estou tentando entender.",
    "Talvez seja por isso que eu esteja escrevendo tudo isso.",
    "Eu não sei exatamente qual é a melhor decisão. Só sei que, do jeito que as coisas estão dentro de mim, talvez um pouco de distância seja necessária.",
    "Não porque você tenha feito algo imperdoável.",
    "Não porque eu queira apagar a nossa amizade.",
    "E muito menos porque eu deixei de me importar.",
    "É justamente porque eu me importo que estou tentando pensar antes que alguma coisa se torne irreversível.",
    "Eu tenho muitos defeitos. Sou impulsivo, muitas vezes imaturo e, em alguns momentos, posso ser extremamente difícil de lidar. Já passei por períodos muito ruins, já ouvi coisas que me machucaram profundamente e já carreguei sentimentos que não soube como administrar.",
    "Mas eu também sei que ter sofrido não me dá o direito de fazer outras pessoas sofrerem.",
    "Essa é uma das coisas que mais me fazem pensar.",
    "Às vezes, quando você respondia apenas “tá bom”, “aham” ou alguma coisa curta, eu começava a imaginar que você estava com raiva de mim. Talvez fosse apenas uma resposta normal. Talvez você nem estivesse pensando naquilo da maneira que eu imaginava.",
    "Mas minha cabeça transformava pequenas coisas em grandes problemas.",
    "E eu não quero continuar fazendo isso.",
    "Não quero continuar interpretando cada silêncio, cada resposta curta e cada mudança como se fosse uma prova de que alguém está cansado de mim.",
    "Também não quero continuar perturbando você simplesmente porque tenho medo de perder sua atenção.",
    "Por isso, talvez eu precise aprender a ficar em silêncio.",
    "Aprender a respeitar o espaço dos outros.",
    "Aprender que gostar de alguém também significa saber deixar essa pessoa livre.",
    "Talvez eu precise me afastar um pouco para conseguir entender tudo isso sem transformar você em responsável por resolver aquilo que existe dentro de mim.",
    "Eu não estou escrevendo isso para que você diga que eu sou uma boa pessoa.",
    "Também não quero que você tente me convencer de que tudo está bem se não estiver.",
    "Se alguma coisa que eu fiz te machucou, eu prefiro que você seja sincera comigo.",
    "Talvez algumas verdades doam, mas eu prefiro uma verdade dolorosa a continuar vivendo dentro de uma versão das coisas que só existe na minha cabeça.",
    "E existe uma última coisa que eu não queria esconder.",
    "Eu ainda amo você.",
    "Talvez seja justamente por isso que escrever esta carta seja tão difícil.",
    "Eu não sei se esse sentimento deveria existir, nem sei o que fazer com ele. Só sei que fingir que ele não existe seria mentir.",
    "Mas gostar de alguém não significa possuir essa pessoa.",
    "Amar alguém não significa exigir que ela fique.",
    "E, se um dia a melhor coisa que eu puder fazer por você for me afastar, então talvez eu precise aprender a fazer isso, mesmo que doa.",
    "Não quero que você guarde de mim apenas a imagem de alguém inconveniente, infantil ou complicado.",
    "Eu sei que fui essas coisas em muitos momentos.",
    "Mas também espero que, algum dia, você consiga enxergar que por trás de tudo isso existia alguém tentando aprender, mesmo errando muitas vezes.",
    "Desculpa por tudo que fiz e por tudo que talvez eu ainda não tenha percebido que fiz.",
    "Desculpa pelas vezes em que procurei atenção demais.",
    "Desculpa pelas vezes em que coloquei meus sentimentos acima dos seus.",
    "Desculpa pelas vezes em que tentei ser prioridade quando eu deveria apenas ter sido seu amigo.",
    "E, acima de tudo, desculpa se em algum momento estar perto de mim deixou de ser algo bom para você.",
    "Eu não sei exatamente o que vai acontecer depois desta carta.",
    "Talvez a gente se afaste.",
    "Talvez continuemos conversando de alguma maneira.",
    "Talvez o tempo faça aquilo que eu não consigo fazer agora.",
    "Eu só precisava que, antes de qualquer decisão, você soubesse o que realmente estava acontecendo dentro de mim.",
    "Não quero que você interprete meu silêncio como ódio.",
    "Não quero que pense que eu deixei de me importar.",
    "Às vezes, afastar-se não significa deixar de amar.",
    "Às vezes, significa reconhecer que continuar da mesma maneira pode acabar machucando as duas pessoas.",
    "Obrigado por ter lido até aqui.",
    "E obrigado por todos os momentos que, independentemente de como tudo termine, fizeram parte da minha vida.",
    "Eu realmente espero que você fique bem.",
    "Benjamim"
  ]
};
